import dearpygui.dearpygui as dpg
import webbrowser
import sys
import vlc

# too much variables oof
cuagain_Play = vlc.MediaPlayer("http://azordon.cf/music/cuagain.wav")
ONON_Play = vlc.MediaPlayer("http://azordon.cf/music/ONON.wav")
fearless_Play = vlc.MediaPlayer("http://azordon.cf/music/fearless.wav")
infectious_Play = vlc.MediaPlayer("http://azordon.cf/music/Infectious.wav")
whywelose_Play = vlc.MediaPlayer("http://azordon.cf/music/whyweloss.wav")
candyland_Play = vlc.MediaPlayer("http://azordon.cf/music/candyland.wav")
Flashes_Play = vlc.MediaPlayer("http://azordon.cf/music/Flashes.wav")
howling_Play = vlc.MediaPlayer("http://azordon.cf/music/howling.wav")
myheart_Play = vlc.MediaPlayer("http://azordon.cf/music/myheart.wav")
Dreams_Play = vlc.MediaPlayer("http://azordon.cf/music/Dreams.wav")
skyhigh_Play = vlc.MediaPlayer("http://azordon.cf/music/skyhigh.wav")
earth_Play = vlc.MediaPlayer("http://azordon.cf/music/earth.wav")
hellcat_Play = vlc.MediaPlayer("http://azordon.cf/music/hellcat.wav")
undone_Play = vlc.MediaPlayer("http://azordon.cf/music/undone.wav")
Eclipse_Play = vlc.MediaPlayer("http://azordon.cf/music/Eclipse.wav")
high_Play = vlc.MediaPlayer("http://azordon.cf/music/high.wav")
nova_Play = vlc.MediaPlayer("http://azordon.cf/music/nova.wav")
hope_Play = vlc.MediaPlayer("http://azordon.cf/music/hope.wav")

# button callbacks
def Fearless():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    fearless_Play.play()
    
def infectious():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    infectious_Play.play()

def cuagain():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    cuagain_Play.play()
    
def git():
    webbrowser.open("github.com/zordon1337/NCS-MUSIC-PLAYER")
    
def ONON():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    ONON_Play.play()

def whywelose():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    whywelose_Play.play()
    
def candyland():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    candyland_Play.play()
    
def Flashes():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    Flashes_Play.play()


def myheart():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    myheart_Play.play()
    
def Dreams():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    Dreams_Play.play()
    

def howling():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    howling_Play.play()

    
def skyhigh():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    skyhigh_Play.play()
    
def hope():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    hope_Play.play()
    
def high():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    high_Play.play()
    
def Eclipse():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    Eclipse_Play.play()
    
def nova():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    nova_Play.play()
    
def Hellcat():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    hellcat_Play.play()
    
def Earth():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    earth_Play.play()
    
def undone():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
    howling_Play.stop()
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    undone_Play.play()
  
def stop():
    cuagain_Play.stop()
    ONON_Play.stop()
    fearless_Play.stop()
    infectious_Play.stop()
    whywelose_Play.stop()
    candyland_Play.stop()
    Flashes_Play.stop()
 
    howling_Play.stop()
 
    myheart_Play.stop()
    Dreams_Play.stop()
    fearless_Play.stop()
    skyhigh_Play.stop()
    earth_Play.stop()
    hellcat_Play.stop()
    high_Play.stop()
    hope_Play.stop()
    Eclipse_Play.stop()
    nova_Play.stop()
    undone_Play.stop()
    

dpg.create_context()

dpg.create_viewport()

dpg.setup_dearpygui()

with dpg.window(label="NCS MUSIC PLAYER - 1.4.3", pos=(425, 150), width=480, height=500) as main_window:
    
    dpg.add_text("Note: you must wait 1 sec until song will load because my site is little slow")
    dpg.add_text("Select music that you want play")
    dpg.add_button(label="Lost Sky - Fearless pt.II", callback=Fearless)
    dpg.add_button(label="Cartoon - C U Again feat. Mikk Mäe", callback=cuagain)
    dpg.add_button(label="Tobu - Infectious", callback=infectious)
    dpg.add_button(label="Cartoon - On & On (feat. Daniel Levi)", callback=ONON)
    dpg.add_button(label="Cartoon - Why We Lose (feat. Coleman Trapp)", callback=whywelose)
    dpg.add_button(label="Tobu - Candyland [NCS Release]", callback=candyland)
    dpg.add_button(label="NIVIRO - Flashes [NCS Release]", callback=Flashes)
    dpg.add_button(label="Different Heaven & EH!DE - My Heart [NCS Release]", callback=myheart)
    dpg.add_button(label="Lost Sky - Dreams", callback=Dreams)
    dpg.add_button(label="Elektronomia - Sky High [NCS Release]", callback=skyhigh)
    dpg.add_button(label="Cartoon - Howling (Ft. Asena) [NCS Release]", callback=howling)   
    dpg.add_button(label="Tobu - Hope [NCS Release]", callback=hope)   
    dpg.add_button(label="JPB - High [NCS RELEASE]", callback=high)
    dpg.add_button(label="Jim Yosef - Eclipse [NCS Release]", callback=Eclipse)
    dpg.add_button(label="Desmeon - Undone (feat. Steklo) [NCS Release]", callback=undone)
    dpg.add_button(label="Ahrix - Nova", callback=nova)
    dpg.add_button(label="Earth - K-391", callback=Earth)
    dpg.add_button(label="DESMEON - HELLCAT [NCS RELEASE]", callback=Hellcat)
    dpg.add_text("Other buttons :)")
    dpg.add_button(label="Stop playing music", callback=stop)   
    dpg.add_button(label="Github", callback=git)
    dpg.add_text("Created by Zordon1337")
    


dpg.show_viewport()

dpg.start_dearpygui()

dpg.destroy_context()